
version: "2"
services:
  websvc:
    build: .
    ports:
      - "3333:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://tattersail:whiskeyjack@websvcdb:5432/app_development
      - TEST_DATABASE_URL=postgresql://tattersail:whiskeyjack@websvcdb:5432/app_test
      - PORT=3000
    depends_on:
      - websvcdb
    command:
        - "ruby ./wait-for-postgres.rb && rails db:migrate && rm -f /opt/app/tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - .:/opt/app
  websvcdb:
    image: postgres:9.6.5-alpine
    environment:
      - POSTGRES_USER=tattersail
      - POSTGRES_PASSWORD=whiskeyjack
      - POSTGRES_DB=app_development
