Description: >

    This stack contains the ECR repository which will hold the images for our
    built application. We allow any users associated with this account (e.g.
    the one used by CircleCI) to push/push to/from this repository.

Parameters:

    RepositoryName:
        Description: The name of the ECR repository
        Type: String

Resources:

    ContinuousIntegrationUser:
        Type: "AWS::IAM::User"
        Properties:
            ManagedPolicyArns:
              - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
              - arn:aws:iam::aws:policy/AmazonECS_FullAccess
            UserName: ContinuousIntegrationUser

    ContinuousIntegrationAccessKey:
        DependsOn: ContinuousIntegrationUser
        Type: "AWS::IAM::AccessKey"
        Properties:
            UserName: ContinuousIntegrationUser

    DemoRepository:
        Type: "AWS::ECR::Repository"
        Properties:
            RepositoryName: !Ref RepositoryName
            RepositoryPolicyText:
                Version: "2012-10-17"
                Statement:
                    -
                        Sid: AllowPushPull
                        Effect: Allow
                        Principal:
                            AWS:
                                !Ref AWS::AccountId
                        Action:
                            - "ecr:*"
                            - "ecr:GetAuthorizationToken"

Outputs:
    ContinuousIntegrationAccessKeyId:
        Description: CI Access Key ID
        Value: !Ref ContinuousIntegrationAccessKey

    ContinuousIntegrationSecretAccessKey:
        Description: CI Secret Access Key
        Value: !GetAtt ContinuousIntegrationAccessKey.SecretAccessKey
